### ISSUE TITLE
Hello author, I would like to ask if these codes can be run on a normal computer ？

### ISSUE THREAD

**Issue by hhhello2022** [MasterXiong/ModuMorph#2]
I would like to ask if these codes can be run on a normal computer ？

**Comment by juanjuanjuanbing** [comment]
I set the num of envs to 16，batch size to 512，which only uses 4g memory，and it can be run on 4060ti

**Comment by MasterXiong** [comment]
I'm not sure what's the hardware available on your computer, but @juanjuanjuanbing 's reply seems to be a good data point for your reference. In general, reducing environment number and the minibatch size of PPO update are good strategies to reduce GPU memory usage.
